package com.jefisu.domain.util

enum class DataMessage : Message {
    SUBSCRIPTION_NOT_DELETED,
    SUBSCRIPTION_DELETED,
    CATEGORY_NAME_CAN_T_BE_BLANK,
    CATEGORY_BUDGET_CAN_T_BE_ZERO,
    CATEGORY_NOT_DELETED,
    CATEGORY_DELETED,
    SUBSCRIPTION_PRICE_CAN_T_BE_ZERO,
    FUNCTIONALITY_UNAVAILABLE,
    CARD_NOT_ADDED,
    CARD_NOT_DELETED,
    CATEGORY_NOT_ADDED,
    SUBSCRIPTION_NOT_ADDED,
    UNKNOWN_ERROR,
}