package com.jefisu.domain.util

enum class DataMessage : Message {
    SUBSCRIPTION_REMOVED,
    SUBSCRIPTION_REMOVAL_FAILED,
    CATEGORY_NAME_REQUIRED,
    CATEGORY_BUDGET_REQUIRED,
    CATEGORY_REMOVED,
    CATEGORY_REMOVAL_FAILED,
    SUBSCRIPTION_PRICE_REQUIRED,
    FUNCTIONALITY_UNAVAILABLE,
    CARD_ADDITION_FAILED,
    CARD_REMOVAL_FAILED,
    CATEGORY_ADDITION_FAILED,
    SUBSCRIPTION_ADDITION_FAILED,
    UNKNOWN_ERROR,
    NO_DATA_AVAILABLE,
}
