name: Deploy to Google Play Store

on:
  workflow_dispatch:

jobs:
  distribute:
    name: Distribute bundle to Google Play
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup local.properties
        run: |
          echo "FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}" >> local.properties
          echo "FACEBOOK_LOGIN_PROTOL_SCHEME=${{ secrets.FACEBOOK_LOGIN_PROTOL_SCHEME }}" >> local.properties
          echo "FACEBOOK_CLIENT_TOKEN=${{ secrets.FACEBOOK_CLIENT_TOKEN }}" >> local.properties
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> local.properties
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> local.properties
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> local.properties
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> local.properties
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> local.properties
          echo "IMGBB_KEY=${{ secrets.IMGBB_KEY }}" >> local.properties

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: '0.${{ github.run_number }}'

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.jefisu.trackizer
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: 'internal'
          status: 'draft'